//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.468
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExpressCss.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ExpressCss.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (function () {
        ///    var script = getScriptInfo(),
        ///        stylesheets = getLocalStylesheets(),
        ///        head = document.getElementsByTagName(&quot;head&quot;)[0];
        ///
        ///    function go() {
        ///        $(function () {
        ///            var connection;
        ///            function connect() {
        ///                if (connection) return;
        ///                connection = $.connection(&apos;_instantcss/connection&apos;);
        ///                connection.received(function (url) {
        ///                    reloadStylesheet(url);
        ///                });
        ///                 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string install {
            get {
                return ResourceManager.GetString("install", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*! jQuery v1.6.3 http://jquery.com/ | http://jquery.org/license */
        ///(function(a,b){function cu(a){return f.isWindow(a)?a:a.nodeType===9?a.defaultView||a.parentWindow:!1}function cr(a){if(!cg[a]){var b=c.body,d=f(&quot;&lt;&quot;+a+&quot;&gt;&quot;).appendTo(b),e=d.css(&quot;display&quot;);d.remove();if(e===&quot;none&quot;||e===&quot;&quot;){ch||(ch=c.createElement(&quot;iframe&quot;),ch.frameBorder=ch.width=ch.height=0),b.appendChild(ch);if(!ci||!ch.createElement)ci=(ch.contentWindow||ch.contentDocument).document,ci.write((c.compatMode===&quot;CSS1Compat&quot;?&quot;&lt;!doctype html&gt;&quot;:&quot;&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string jquery {
            get {
                return ResourceManager.GetString("jquery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to var JSON;if(!JSON)JSON={};(function(){&quot;use strict&quot;;function c(a){return a&lt;10?&quot;0&quot;+a:a}if(typeof Date.prototype.toJSON!==&quot;function&quot;){Date.prototype.toJSON=function(){return isFinite(this.valueOf())?this.getUTCFullYear()+&quot;-&quot;+c(this.getUTCMonth()+1)+&quot;-&quot;+c(this.getUTCDate())+&quot;T&quot;+c(this.getUTCHours())+&quot;:&quot;+c(this.getUTCMinutes())+&quot;:&quot;+c(this.getUTCSeconds())+&quot;Z&quot;:null};String.prototype.toJSON=Number.prototype.toJSON=Boolean.prototype.toJSON=function(){return this.valueOf()}}var h=/[\u0000\u00ad\u0600-\u0604\u070f\u1 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string json2 {
            get {
                return ResourceManager.GetString("json2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (function(n,t){&quot;use strict&quot;;if(typeof n!=&quot;function&quot;)throw&quot;SignalR: jQuery not found. Please ensure jQuery is referenced before the SignalR.js file.&quot;;if(!t.JSON)throw&quot;SignalR: No JSON parser found. Please ensure json2.js is referenced before the SignalR.js file if you need to support clients without native JSON parsing support, e.g. IE&lt;8.&quot;;var i,r;i=function(n){return new i.fn.init(n)},i.fn=i.prototype={init:function(n){this.url=n},start:function(r,u){var f=this,e={transport:&quot;auto&quot;},o;return f.transport?f:(n [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string signalr {
            get {
                return ResourceManager.GetString("signalr", resourceCulture);
            }
        }
    }
}
